#!/bin/bash
#SBATCH -p gpu
#SBATCH --gres=gpu:v100:1
#SBATCH -J ratio-extract
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --time=1-1:00:00
#SBATCH -o log
#SBATCH --mail-user=dncross
#SBATCH --mail-type=BEGIN,END

module load cudatoolkit
module load python
export OMP_NUM_THREADS=8

#python extract_ratios_percentile.py 0p3 --is_2D=True
#python extract_ratios_percentile.py 0p6 --is_2D=True
#python extract_ratios_percentile.py 1p2 --is_2D=True

python extract_ratios_percentile.py 0p3 --lower_shell=0.0 --upper_shell=0.1 
python extract_ratios_percentile.py 0p6 --lower_shell=0.0 --upper_shell=0.1 
python extract_ratios_percentile.py 1p2 --lower_shell=0.0 --upper_shell=0.1 

python extract_ratios_percentile.py 0p3 --lower_shell=0.1 --upper_shell=0.2 
python extract_ratios_percentile.py 0p6 --lower_shell=0.1 --upper_shell=0.2 
python extract_ratios_percentile.py 1p2 --lower_shell=0.1 --upper_shell=0.2 

python extract_ratios_percentile.py 0p3 --lower_shell=0.2 --upper_shell=0.3 
python extract_ratios_percentile.py 0p6 --lower_shell=0.2 --upper_shell=0.3 
python extract_ratios_percentile.py 1p2 --lower_shell=0.2 --upper_shell=0.3 

python extract_ratios_percentile.py 0p3 --lower_shell=0.3 --upper_shell=0.4
python extract_ratios_percentile.py 0p6 --lower_shell=0.3 --upper_shell=0.4 
python extract_ratios_percentile.py 1p2 --lower_shell=0.3 --upper_shell=0.4 

python extract_ratios_percentile.py 0p3 --lower_shell=0.4 --upper_shell=0.5 
python extract_ratios_percentile.py 0p6 --lower_shell=0.4 --upper_shell=0.5 
python extract_ratios_percentile.py 1p2 --lower_shell=0.4 --upper_shell=0.5 

python extract_ratios_percentile.py 0p3 --lower_shell=0.5 --upper_shell=0.6 
python extract_ratios_percentile.py 0p6 --lower_shell=0.5 --upper_shell=0.6 
python extract_ratios_percentile.py 1p2 --lower_shell=0.5 --upper_shell=0.6 

python extract_ratios_percentile.py 0p3 --lower_shell=0.6 --upper_shell=0.7 
python extract_ratios_percentile.py 0p6 --lower_shell=0.6 --upper_shell=0.7 
python extract_ratios_percentile.py 1p2 --lower_shell=0.6 --upper_shell=0.7 

python extract_ratios_percentile.py 0p3 --lower_shell=0.7 --upper_shell=0.8 
python extract_ratios_percentile.py 0p6 --lower_shell=0.7 --upper_shell=0.8 
python extract_ratios_percentile.py 1p2 --lower_shell=0.7 --upper_shell=0.8 

python extract_ratios_percentile.py 0p3 --lower_shell=0.8 --upper_shell=0.9 
python extract_ratios_percentile.py 0p6 --lower_shell=0.8 --upper_shell=0.9 
python extract_ratios_percentile.py 1p2 --lower_shell=0.8 --upper_shell=0.9 

python extract_ratios_percentile.py 0p3 --lower_shell=0.9 --upper_shell=1.0 
python extract_ratios_percentile.py 0p6 --lower_shell=0.9 --upper_shell=1.0 
python extract_ratios_percentile.py 1p2 --lower_shell=0.9 --upper_shell=1.0 



